// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAllBackupStates():Promise<Record<string, main.BackupState>>;

export function GetBackupState():Promise<main.BackupState>;

export function GetSuggestedBackupPaths():Promise<Array<string>>;

export function GetSuggestedIgnorePatterns():Promise<Array<string>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function PauseBackup():Promise<void>;

export function RestartBackup(arg1:main.BackupConfig):Promise<void>;

export function ResumeBackup():Promise<void>;

export function SelectDestinationDirectory():Promise<string>;

export function SelectSourceDirectory():Promise<string>;

export function SetSavedBackups(arg1:Array<main.BackupConfig>):Promise<void>;

export function StartBackup(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function StopBackup():Promise<void>;

export function TestConnection():Promise<string>;

export function ValidateBackupPath(arg1:string):Promise<boolean>;
