// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSuggestedBackupPaths():Promise<Array<string>>;

export function GetSuggestedIgnorePatterns():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SelectDestinationDirectory():Promise<string>;

export function SelectSourceDirectory():Promise<string>;

export function StartBackup(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;
