// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSuggestedBackupPaths() {
  return window['go']['main']['App']['GetSuggestedBackupPaths']();
}

export function GetSuggestedIgnorePatterns() {
  return window['go']['main']['App']['GetSuggestedIgnorePatterns']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDestinationDirectory() {
  return window['go']['main']['App']['SelectDestinationDirectory']();
}

export function SelectSourceDirectory() {
  return window['go']['main']['App']['SelectSourceDirectory']();
}

export function StartBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBackup'](arg1, arg2, arg3);
}

export function ValidateBackupPath(arg1) {
  return window['go']['main']['App']['ValidateBackupPath'](arg1);
}
